# More info on config here: https://github.com/golangci/golangci-lint#config-file
linters:
  disable-all: true
#   enable:
#     - revive
#     - govet
#     - errcheck
#     - ineffassign
#     - typecheck
#     - gosec
#     - goimports
#     - gosimple
#     - unused
#     - staticcheck
#     - gochecknoinits
#     - makezero
#     - whitespace
#     - lll

# linters-settings:
#   gosec:
#     excludes:
#       - G115
#   revive:
#     rules:
#       - name: var-naming # usually this is not critical
#         disabled: true
#   govet:
#     enable-all: true
#     disable:
#       - fieldalignment
#       - shadow
#       - nilness
#       - unusedwrite
#   lll:
#     line-length: 120
#   staticcheck:
#     checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-SA1019" ]

# issues:
#   exclude-rules:
#     - linters:
#         - lll
#       source: "// tagID \\d+ "
#     - linters:
#         - lll
#       source: "getTypedHandler"
#     - path: '(.+)_test\.go'
#       linters:
#         - gosec
#         - funlen